model:
  _target_: dit.get_model
  backbone_type: DiT-B/2
  params:
    num_classes: ${dataset.num_classes}
    in_channels: ${dataset.num_channels}
    input_size: 256
    cond_mode: adaln
    enable_routing: True
    routes:
      - selection_ratio: 0.5
        start_layer_idx: 0
        end_layer_idx: 8
        x_T: True
        x_D_last: True 